### PR TITLE
update compressinglibs dependency

### PR DESCRIPTION
**Pull request by marina-manrique**

### CODE REVIEW

**Comment by laughedelic** [comment]
I think you can merge it

**Comment by marina-manrique** [comment]
Did you publish the artifact?

**Comment by laughedelic** [comment]
yes

**Comment by laughedelic** [comment]
btw, I'm going to clean up all those artifacts with the old `ohnosequencesBundles` org, because if it appears somewhere by accident it resolves and brings a lot of confusion

**Comment by marina-manrique** [comment]
:+1:

**Comment by laughedelic** [comment]
done :ok_hand:

**Comment by marina-manrique** [comment]
BTW what do you mean by 

> clean up all those artifacts with the old ohnosequencesBundles org

just deleting the artifacts or you are updating the bundles code, publishing and updating the dep in `bundles` ?

**Comment by laughedelic** [comment]
> updating the bundles code, publishing and updating the dep in bundles

I've done that yesterday already :wink: 

> deleting the artifacts

and this too, just now :grin:

**Comment by marina-manrique** [comment]
wow cool, all these changes are merged in the master branch of each repo?

**Comment by laughedelic** [comment]
no, because I thought that you probably were going to do something before merging them.

**Comment by marina-manrique** [comment]
:+1: I'm reviewing and merging

**Pull request merged**
